#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Copyright (c) 2011 Nicolai Hähnle <nhaehnle@gmail.com>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.
#

"""
Command-line utility
"""

import argparse
import re
import sys

import patre
import patre.compile
import patre.cpp
import patre.nfa
import patre.text

## GLOBAL VARIABLES AND ARGUMENTS
editor = None
currentfiletext = None
nfa = patre.nfa.Nfa()
options = patre.compile.Options(patre.cpp.tokenizer, patre.cpp.treeify)

globalstart = nfa.newstate()
nfa.transition(globalstart, globalstart, match=patre.nfa.nfa_list(nfa, 0, -1))
nfa.transition(globalstart, globalstart, match=patre.nfa.nfa_any())

parser = argparse.ArgumentParser(description='Parenthesis-aware context-free grammar based file processing.')
parser.add_argument('script', metavar='script', type=str, help='CFG definition and command script')
parser.add_argument('inputs', metavar='FILE', type=str, nargs='*', help='input file(s); if not set, read from STDIN')
parser.add_argument('--debug', '-d', action='store_true', help='print debugging output')
parser.add_argument('--inplace', '-i', action='store_true', help='modify input files in place instead of writing to STDOUT')

args = parser.parse_args()

## SUBROUTINES

def make_program(startstate, endstate, lst):
	nfa.transition(globalstart, startstate, match=None)

	execstate = nfa.newstate()
	t = nfa.transition(endstate, execstate, match=None)
	t.callback = lambda kv: run_program(lst, kv)

def prog_get_pos(kv, arg):
	s = arg.split('.')
	if len(s) == 2:
		pos = getattr(kv[s[0]], s[1])
	else:
		pos = kv[arg]
	if type(pos) != int:
		raise ValueError('%s does not name an int' % (arg))
	return pos

def prog_get_start_end(kv, args):
	if len(args) == 1:
		start = kv[args[0]].start
		end = kv[args[0]].end
	else:
		start = prog_get_pos(kv, args[0])
		end = prog_get_pos(kv, args[1])
	return start, end

def do_run_program(lst, kv):
	if args.debug:
		print "run_program", lst, kv

	idx = 0
	while idx < len(lst):
		linenr, line = lst[idx]

		if line[0] == "replace":
			if len(line) == 4:
				start,end = prog_get_start_end(kv, line[1:3])
				template = line[3]
			else:
				start,end = prog_get_start_end(kv, line[1:2])
				template = line[2]
			editor.erase(start, end)
			editor.insert(start, template.format(**kv))
		elif line[0] == "erase":
			start,end = prog_get_start_end(kv, line[1:])
			editor.erase(start, end)
		elif line[0] == "insert":
			pos = prog_get_pos(kv, line[1])
			editor.insert(pos, line[2].format(**kv))
		elif line[0] == "forall":
			idx += 1
			for subkv in kv[line[1]]:
				callkv = kv.copy()
				callkv.update(subkv)
				do_run_program(lst[idx], callkv)
		elif line[0] == "if":
			idx += 1
			if line[1] in kv and kv[line[1]]:
				do_run_program(lst[idx], kv)
		elif line[0] == "letrange":
			start,end = prog_get_start_end(kv, line[2:])
			kv[line[1]] = patre.text.TextRange(currentfiletext, start, end)
		elif line[0] == "letregex":
			m = re.match(line[3], str(kv[line[2]]))
			if not m:
				raise ValueError("%d: regular expression did not match '%s'" % (linenr, kv[line[2]]))
			kv[line[1]] = m.groups()[0]
		else:
			raise ValueError("%d: unknown command %s" % (linenr, line[0]))
		idx += 1

def translate_dictionary(kv):
	newkv = {}
	for key in kv.iterkeys():
		if type(key) == tuple:
			name = key[0]
			if not name in newkv:
				newkv[name] = patre.text.TextRange(currentfiletext, kv[(name,0)], kv[(name,1)])
		else:
			value = kv[key]
			if type(value) == list:
				newkv[key] = [translate_dictionary(d) for d in value if d]
			else:
				newkv[key] = value
	return newkv

def run_program(lst, kv):
	do_run_program(lst, translate_dictionary(kv))

def parse_line(line):
	white = re.compile("\\s*")
	nonwhite = re.compile("\\S*")

	fields = []
	pos = 0
	while pos < len(line):
		pos = white.match(line, pos).end()
		if pos >= len(line):
			break

		if line[pos] == '"':
			s = ""
			pos += 1
			while pos < len(line):
				if line[pos] == '"':
					pos += 1
					break
				for esc,to in [ ('\\n', '\n'), ('\\"', '\"'), ('\\t', '\t') ]:
					if line.startswith(esc, pos):
						pos += len(esc)
						s += to
						break
				else:
					s += line[pos]
					pos += 1
			else:
				raise ValueError("unmatched quotation mark")
			fields.append(s)
		else:
			end = nonwhite.match(line, pos).end()
			fields.append(line[pos:end])
			pos = end

	return fields

def get_indent(line):
	pos = 0
	while pos < len(line) and line[pos] in [ ' ', '\t', '\n' ]:
		pos += 1
	if pos >= len(line) or line[pos] == '#':
		return "", ""

	return line[:pos], line[pos:].strip()

def parse_script(fname):
	global productions
	global programs

	filp = open(fname, 'r')
	sub = None
	lst = None
	indents = None

	linenr = 0
	for line in filp:
		linenr += 1

		if sub != None:
			indent, line = get_indent(line)
			if not line:
				continue

			if indent:
				if not indents:
					indents = [indent]
					lst = [[]]
				else:
					if len(indent) > len(indents[-1]):
						if not indent.startswith(indents[-1]):
							print >>sys.stderr, "%d: bad indentation" % (linenr)
							exit(1)
						indents.append(indent)
						lst.append([])
						lst[-2].append(lst[-1])
					else:
						while indents and len(indent) < len(indents[-1]):
							indents.pop()
							lst.pop()
						if not indents or indent != indents[-1]:
							print >>sys.stderr, "%d: bad indentation" % (linenr)

				lst[-1].append((linenr, parse_line(line)))
				continue

			sub(lst[0])
			lst = None
			indents = None
			sub = None

		line = line.strip()
		if not line or line[0] == '#':
			continue

		m = re.match("match \\s+ (.+)", line, re.VERBOSE)
		if m:
			expr = m.groups()[0]
			startstate, endstate = patre.compile.compile(nfa, expr, options)
			sub = lambda lst: make_program(startstate, endstate, lst)
			continue

		m = re.match("define \\s+ (\\w+) \\s+ (.+)", line, re.VERBOSE)
		if m:
			tag = m.groups()[0]
			expr = m.groups()[1]
			if tag in options.tags:
				print >>sys.stderr, "%d: multiply defined '%s'" % (linenr, tag)
				exit(1)

			subnfa = patre.nfa.Nfa()
			startstate, endstate = patre.compile.compile(subnfa, expr, options)
			options.tags[tag] = (subnfa, startstate, endstate)
			continue

		print >>sys.stderr, "%d: unknown command" % (linenr)
		exit(1)

	if sub != None:
		sub(lst[0])

## MAIN PROGRAM
parse_script(args.script)

if args.debug:
	nfa.write()
	nfa.debug = True

if args.inputs:
	for fname in args.inputs:
		with open(fname, 'r') as filp:
			currentfiletext = filp.read()

		editor = patre.text.Editor()

		tree = options.treeify.maketree(options.tokenizer(currentfiletext)())
		nfa(tree, globalstart)

		if args.inplace:
			with open(fname, 'w') as filp:
				print >>filp, editor.apply(currentfiletext),
		else:
			print editor.apply(currentfiletext),
else:
	currentfiletext = sys.stdin.read()

	editor = patre.text.Editor()

	tree = options.treeify.maketree(options.tokenizer(currentfiletext)())
	nfa(tree, globalstart)

	print editor.apply(currentfiletext),
